### ISSUE TITLE
Add EEPROM support

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MCP4725#16]
The MCP4725 has the ability to store the DAC value in EEPROM so it persists with power cycle. Looks like the library currently only support writing in "fast mode", which does not write to EEPROM:
![dac_eeprom](https://user-images.githubusercontent.com/8755041/90928474-c5765200-e3ab-11ea-8dac-918915bb6f78.png)

Re this thread:
https://forums.adafruit.com/viewtopic.php?f=24&t=168627

**Comment by caternuson** [comment]
How about a new method called something like `save_current()` or `save_to_eeprom()`? It would take whatever the current DAC value is and write it to EEPROM. Something like this:
```python
dac.value = 23
dac.save_to_eeprom()
```

The other idea would be a new property. But since there's no way to write to *just* EEPROM, not sure that makes sense.

**Comment by siddacious** [comment]
🤔 I _thought_ I had enabled saving to EEPROM, but perhaps I'm mistaken. If it's not there, it should be. I belive in another lib I had a `default_value` property or something similar; either approach could work. Some of the nit-picky details of the verbage to use could depend on the overall behavior.

**Comment by caternuson** [comment]
The issue with a property is it would also change the current value being output on the DAC. Which might be an unexpected behavior. At least I'm not seeing a way to write to *only* the EEPROM. If there is, then yah, let's use a property.

The Arduino library does it via a boolean parameter:
https://github.com/adafruit/Adafruit_MCP4725/blob/d04eeb23a3621f1718603a73448a53c8a79e4627/Adafruit_MCP4725.cpp#L69
but since we're using Python properties, need to do something different here. I think?

**Comment by caternuson** [comment]
Added with #17
