### ISSUE TITLE
starting output voltage during power on .

### ISSUE THREAD

**Issue by rr3511** [adafruit/Adafruit_CircuitPython_MCP4725#18]
As per datasheet Vout = Vdd*0.5 . It causes problem on my project ,as per project no voltages should in output pin during power on .
Can you please suggest me how to overcome this issue.
As saving to eeprom also started with previous value ,So it causes same issue in abnormal power interruption time.

**Comment by siddacious** [comment]
@rr3511 Please post in the adafruit forums for support:
https://forums.adafruit.com/viewforum.php?f=60
