### ISSUE TITLE
Add Mock Library to support development outside RPi

### ISSUE THREAD

**Issue by codenio** [adafruit/Adafruit_CircuitPython_MCP4725#19]
Hi, adding a mock package in this same library, would allow people to develop their code outside RPi

I am currently using the following way to mock adafruit_mcp4725 outside RPi, and it works.

```python
try:
    import RPi.GPIO as GPIO
    import adafruit_mcp4725
except:
    import Mock.GPIO as GPIO
    import adafruit_mcp4725.mock as adafruit_mcp4725
```

Thoughts..?

**Comment by ladyada** [comment]
please do not open multiple issues for the same q thx!
