### ISSUE TITLE
Convert to busdevice use.

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MCP4725#8]
This library is using the I2C bus directly and manually managing locking/unlocking. It should be converted to use BusDevice. See example [here](https://circuitpython.readthedocs.io/en/latest/docs/design_guide.html#i2c-example).

**Comment by ladyada** [comment]
yah this was one of the first libraries written :)

**Comment by caternuson** [comment]
Yep, was just doing some housekeeping and came across your comment in #7. Figured a separate issue would be good for tracking and visibility.

**Comment by caternuson** [comment]
Fixed with #9
